spring.application.name=api-users_square-game
spring.profiles.active=mysql
server.port=8081

### À mettre dans un fichier application-local.properties###
jwt.secret=ta-cle-secrete-tres-longue-et-difficile-a-deviner
